export const ADD_INVESTMENT = "ADD_INVESTMENT";
export const UPDATE_INVESTMENT = "UPDATE_INVESTMENT";
export const DELETE_INVESTMENT = "DELETE_INVESTMENT";
export const TOGGLE_NAVBAR = "TOGGLE_NAVBAR";
export const CHANGE_THEME = "CHANGE_THEME";
